# Generated by Django 4.1 on 2022-08-19 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_remove_user_following_user_followers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='followers',
            new_name='follows',
        ),
    ]
