# Generated by Django 4.0.3 on 2022-03-29 12:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_createlisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='createlisting',
            name='watchlist_user',
            field=models.ManyToManyField(blank=True, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
