# Generated by Django 4.0.3 on 2022-03-29 13:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_createlisting_watchlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createlisting',
            name='watchlist_user',
            field=models.ManyToManyField(blank=True, related_name='item', to=settings.AUTH_USER_MODEL),
        ),
    ]
