# Generated by Django 4.0.3 on 2022-03-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_bid_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='createlisting',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
