# Generated by Django 4.0.3 on 2022-03-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_createlisting_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createlisting',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
