# Generated by Django 4.0.3 on 2022-03-30 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_createlisting_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createlisting',
            old_name='active',
            new_name='inactive',
        ),
    ]
