# Generated by Django 4.0.3 on 2022-03-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_rename_active_createlisting_inactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createlisting',
            name='inactive',
            field=models.BooleanField(default=False),
        ),
    ]
