# Generated by Django 4.0.3 on 2022-03-31 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_alter_createlisting_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='createlisting',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
