# Generated by Django 4.0.3 on 2022-03-31 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_createlisting_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createlisting',
            old_name='date',
            new_name='date_time',
        ),
    ]
