# Generated by Django 4.0.3 on 2022-03-31 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_alter_createlisting_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createlisting',
            name='date_time',
        ),
    ]
