# Generated by Django 4.0.3 on 2022-03-31 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_remove_createlisting_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='createlisting',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
